---
- name: Install podman in Debian Distro
  ansible.builtin.apt:
    name: "{{ item ~ '=' ~ podman_version if item == 'podman' and podman_version != 'latest' else item }}"
    state: "{{ 'latest' if item == 'podman' and podman_version == 'latest' else 'present' }}"
    allow_downgrade: "{{ podman_version != 'latest' }}"
    update_cache: yes
  loop: "{{ _apt }}"
  register: result
  until: result is succeeded
  notify: Restart podman service
